// ============================================================
// LLM Service — Abstracted orchestration layer
// Routes through Groq API when key is available, otherwise
// falls back to the high-fidelity mock engine.
// ============================================================

import type {
  CharacterVoiceProfile,
  ComicPanel,
  Genre,
  LLMSettings,
  TargetFormat,
  DeliveryStyle,
} from '../types/comic';
import { callGroq } from './groqApi';
import {
  mockRefineStory,
  mockExtractCharacters,
  mockGenerateBreakdown,
  mockGenerateDialogue,
  mockRegeneratePanel,
} from './mockGenerators';
import { getFormatPanelCount } from '../types/comic';

function hasApiKey(settings: LLMSettings): boolean {
  const key = settings.apiKey || (import.meta.env.VITE_GROQ_API_KEY as string) || '';
  return Boolean(key && key.trim().length > 5);
}

function safeJsonParse<T>(text: string, fallback: T): T {
  try {
    // Try to extract JSON from markdown code blocks if present
    const jsonMatch = text.match(/```(?:json)?\s*([\s\S]*?)```/);
    const cleanText = jsonMatch ? jsonMatch[1].trim() : text.trim();
    return JSON.parse(cleanText);
  } catch {
    console.warn('Failed to parse LLM JSON response, using fallback');
    return fallback;
  }
}

// ──────────────────────────────────────────────
// 1. Story Refinement
// ──────────────────────────────────────────────
export async function refineStory(
  story: string,
  genre: Genre,
  settings: LLMSettings,
): Promise<string> {
  if (!hasApiKey(settings)) {
    return mockRefineStory(story, genre);
  }

  const result = await callGroq([
    {
      role: 'system',
      content: `You are a master comic book writer and story editor. Refine and enhance the given story idea for a ${genre} comic. 
Make the story more visually compelling, add dramatic beats, sharpen character motivations, and ensure the pacing works for a panel-by-panel visual medium.
Respond with JSON: { "refined_story": "..." }`,
    },
    {
      role: 'user',
      content: `Refine this story for a ${genre} comic:\n\n${story}`,
    },
  ], settings);

  const parsed = safeJsonParse<{ refined_story: string }>(result, { refined_story: story });
  return parsed.refined_story;
}

// ──────────────────────────────────────────────
// 2. Character Extraction from Story
// ──────────────────────────────────────────────
export async function extractCharactersFromStory(
  story: string,
  genre: Genre,
  settings: LLMSettings,
): Promise<CharacterVoiceProfile[]> {
  if (!hasApiKey(settings)) {
    return mockExtractCharacters(story, genre);
  }

  const result = await callGroq([
    {
      role: 'system',
      content: `You are a character design expert for ${genre} comics. Extract all characters from the story and create detailed voice profiles.

For each character, provide:
- name: character name
- physical_description: detailed visual appearance for comic art
- personality: core personality traits
- speech_style: how they talk (sentence structure, quirks, patterns)
- vocabulary_level: their word choice tendencies
- emotional_tendencies: how they handle emotions
- relationships: object mapping other character names to relationship description

Respond with JSON: { "characters": [ { "name": "...", "physical_description": "...", "personality": "...", "speech_style": "...", "vocabulary_level": "...", "emotional_tendencies": "...", "relationships": { "OtherChar": "relationship description" } } ] }`,
    },
    {
      role: 'user',
      content: `Extract characters from this ${genre} story:\n\n${story}`,
    },
  ], settings);

  const parsed = safeJsonParse<{ characters: Omit<CharacterVoiceProfile, 'id' | 'avatarColor' | 'isAutoGenerated'>[] }>(
    result, { characters: [] }
  );

  const avatarColors = ['#6366f1', '#ec4899', '#f59e0b', '#10b981', '#ef4444', '#8b5cf6'];

  return parsed.characters.map((c, i) => ({
    ...c,
    id: Date.now().toString(36) + Math.random().toString(36).slice(2, 8),
    avatarColor: avatarColors[i % avatarColors.length],
    isAutoGenerated: true,
    relationships: c.relationships || {},
  }));
}

// ──────────────────────────────────────────────
// 3. Story Breakdown — Panel planning
// ──────────────────────────────────────────────
export async function generateStoryBreakdown(
  story: string,
  characters: CharacterVoiceProfile[],
  genre: Genre,
  format: TargetFormat,
  settings: LLMSettings,
  onProgress?: (panel: number, total: number) => void,
): Promise<ComicPanel[]> {
  const panelCount = getFormatPanelCount(format);

  if (!hasApiKey(settings)) {
    const panels = await mockGenerateBreakdown(story, characters, genre, format);
    for (let i = 0; i < panels.length; i++) {
      onProgress?.(i + 1, panelCount);
    }
    return panels;
  }

  const characterSummary = characters.map(c => 
    `- ${c.name}: ${c.physical_description}. Personality: ${c.personality}`
  ).join('\n');

  const result = await callGroq([
    {
      role: 'system',
      content: `You are a master ${genre} comic storyboard artist. Break the story into exactly ${panelCount} comic panels.

Each panel represents one visual beat. Focus on:
- Setting (detailed visual description)
- Characters present (from the provided character list)
- Action (what is physically happening)
- Emotion/mood of the scene
- NO dialogue at this stage — pure scene planning

Characters available:
${characterSummary}

Respond with JSON: { "panels": [ { "panel_number": 1, "setting": "...", "characters_present": ["Name"], "action": "...", "emotion": "..." } ] }`,
    },
    {
      role: 'user',
      content: `Break this ${genre} story into ${panelCount} comic panels:\n\n${story}`,
    },
  ], settings);

  const parsed = safeJsonParse<{ panels: Partial<ComicPanel>[] }>(result, { panels: [] });

  return parsed.panels.map((p, i) => {
    onProgress?.(i + 1, panelCount);
    return {
      panel_number: i + 1,
      setting: p.setting || '',
      characters_present: p.characters_present || [],
      action: p.action || '',
      emotion: p.emotion || '',
      dialogue: [],
      narration: '',
      image_prompt: '',
    };
  });
}

// ──────────────────────────────────────────────
// 4. Dialogue Generation — per panel
// ──────────────────────────────────────────────
export async function generatePanelDialogue(
  panel: ComicPanel,
  allPanels: ComicPanel[],
  characters: CharacterVoiceProfile[],
  genre: Genre,
  settings: LLMSettings,
  story?: string,
): Promise<{ dialogue: { speaker: string; line: string; delivery: DeliveryStyle }[]; narration: string; image_prompt: string }> {
  if (!hasApiKey(settings)) {
    return mockGenerateDialogue(panel, characters, genre, story);
  }

  // Build character voice context
  const presentCharacters = characters.filter(c => panel.characters_present.includes(c.name));
  const voiceProfiles = presentCharacters.map(c => 
    `CHARACTER: ${c.name}
Physical: ${c.physical_description}
Personality: ${c.personality}
Speech Style: ${c.speech_style}
Vocabulary: ${c.vocabulary_level}
Emotional Tendencies: ${c.emotional_tendencies}
Relationships: ${Object.entries(c.relationships).map(([k, v]) => `${k}: ${v}`).join(', ')}`
  ).join('\n\n');

  // Previous panel context for continuity
  const prevPanels = allPanels
    .filter(p => p.panel_number < panel.panel_number && p.panel_number >= panel.panel_number - 2)
    .map(p => `Panel ${p.panel_number}: ${p.setting}. ${p.action}. Dialogue: ${p.dialogue.map(d => `${d.speaker}: "${d.line}"`).join(', ')}`)
    .join('\n');

  const result = await callGroq([
    {
      role: 'system',
      content: `You are a master ${genre} comic dialogue writer. Generate character-authentic dialogue for the given panel.

CHARACTER VOICE PROFILES (use these to ensure each character sounds distinct):
${voiceProfiles}

RULES:
- Each character MUST sound like their voice profile
- Dialogue must reflect the panel's emotion: ${panel.emotion}
- Maintain continuity with previous panels
- Include delivery style for each line: normal, shout, whisper, thought, sarcastic, muttered, trembling, cold, excited
- Add narration if dramatically appropriate
- Generate an image_prompt: a plain descriptive text (no platform-specific syntax) describing the visual scene

${prevPanels ? `PREVIOUS PANELS FOR CONTINUITY:\n${prevPanels}` : ''}

Respond with JSON: { "dialogue": [ { "speaker": "Name", "line": "...", "delivery": "normal" } ], "narration": "...", "image_prompt": "..." }`,
    },
    {
      role: 'user',
      content: `Generate dialogue for this panel:\nSetting: ${panel.setting}\nAction: ${panel.action}\nEmotion: ${panel.emotion}\nCharacters: ${panel.characters_present.join(', ')}`,
    },
  ], settings);

  const parsed = safeJsonParse<{ dialogue: { speaker: string; line: string; delivery: DeliveryStyle }[]; narration: string; image_prompt: string }>(
    result,
    { dialogue: [], narration: '', image_prompt: '' }
  );

  return parsed;
}

// ──────────────────────────────────────────────
// 5. Panel Regeneration
// ──────────────────────────────────────────────
export async function regeneratePanel(
  panel: ComicPanel,
  allPanels: ComicPanel[],
  characters: CharacterVoiceProfile[],
  genre: Genre,
  mode: 'scene' | 'dialogue' | 'both',
  settings: LLMSettings,
): Promise<Partial<ComicPanel>> {
  if (!hasApiKey(settings)) {
    return mockRegeneratePanel(panel, characters, genre, mode);
  }

  if (mode === 'dialogue') {
    const dialogueResult = await generatePanelDialogue(panel, allPanels, characters, genre, settings);
    return {
      dialogue: dialogueResult.dialogue,
      narration: dialogueResult.narration,
      image_prompt: dialogueResult.image_prompt,
    };
  }

  // For scene or both, regenerate the full panel
  const voiceProfiles = characters
    .filter(c => panel.characters_present.includes(c.name))
    .map(c => `${c.name}: ${c.personality}, speaks with ${c.speech_style}`)
    .join('\n');

  const result = await callGroq([
    {
      role: 'system',
      content: `Regenerate the ${mode === 'both' ? 'scene and dialogue' : 'scene'} for this ${genre} comic panel.
Keep the same characters. Create a fresh scene with new setting, action, and mood.
${mode === 'both' ? `Also generate new dialogue using these voice profiles:\n${voiceProfiles}` : ''}

Respond with JSON containing the regenerated fields: { "setting": "...", "action": "...", "emotion": "..."${mode === 'both' ? ', "dialogue": [...], "narration": "...", "image_prompt": "..."' : ''} }`,
    },
    {
      role: 'user',
      content: `Regenerate panel ${panel.panel_number}. Current: Setting="${panel.setting}", Action="${panel.action}", Characters=${panel.characters_present.join(', ')}`,
    },
  ], settings);

  return safeJsonParse<Partial<ComicPanel>>(result, {});
}

// ──────────────────────────────────────────────
// 6. Full Pipeline Orchestrator
// ──────────────────────────────────────────────
export async function generateFullScript(
  story: string,
  characters: CharacterVoiceProfile[],
  genre: Genre,
  format: TargetFormat,
  settings: LLMSettings,
  onProgress?: (stage: string, current: number, total: number) => void,
): Promise<ComicPanel[]> {
  const panelCount = getFormatPanelCount(format);

  // Stage 1: Story Breakdown
  onProgress?.('breakdown', 0, panelCount);
  const panels = await generateStoryBreakdown(story, characters, genre, format, settings, (cur, tot) => {
    onProgress?.('breakdown', cur, tot);
  });

  // Stage 2: Dialogue Generation per panel (pass story for mock context)
  for (let i = 0; i < panels.length; i++) {
    onProgress?.('dialogue', i + 1, panels.length);
    const dialogueResult = await generatePanelDialogue(panels[i], panels, characters, genre, settings, story);
    panels[i].dialogue = dialogueResult.dialogue;
    panels[i].narration = dialogueResult.narration;
    panels[i].image_prompt = dialogueResult.image_prompt;
  }

  onProgress?.('complete', panelCount, panelCount);
  return panels;
}
