// ============================================================
// AI Comic Script & Dialogue Generator — Core Data Types
// ============================================================

export type DeliveryStyle =
  | 'normal'
  | 'shout'
  | 'whisper'
  | 'thought'
  | 'sarcastic'
  | 'muttered'
  | 'trembling'
  | 'cold'
  | 'excited'
  | 'narration';

export type Genre =
  | 'noir'
  | 'manga'
  | 'cyberpunk'
  | 'webtoon-romance'
  | 'superhero'
  | 'fantasy'
  | 'comedy'
  | 'horror'
  | 'sci-fi'
  | 'slice-of-life'
  | 'action'
  | 'drama';

export type TargetFormat =
  | '3-panel-strip'
  | '4-panel-strip'
  | '6-panel-scene'
  | '9-panel-page'
  | '12-panel-episode';

export interface CharacterVoiceProfile {
  id: string;
  name: string;
  physical_description: string;
  personality: string;
  speech_style: string;
  vocabulary_level: string;
  emotional_tendencies: string;
  relationships: Record<string, string>;
  avatarColor: string;
  isAutoGenerated: boolean;
}

export interface DialogueItem {
  speaker: string;
  line: string;
  delivery: DeliveryStyle;
}

export interface ComicPanel {
  panel_number: number;
  setting: string;
  characters_present: string[];
  action: string;
  emotion: string;
  dialogue: DialogueItem[];
  narration: string;
  image_prompt: string;
  isGenerating?: boolean;
}

export interface StoryProject {
  id: string;
  title: string;
  story_idea: string;
  refined_story?: string;
  genre: Genre;
  target_format: TargetFormat;
  characters: CharacterVoiceProfile[];
  panels: ComicPanel[];
  createdAt: string;
  updatedAt: string;
}

export interface LLMSettings {
  apiKey: string;
  model: string;
  temperature: number;
  maxTokens: number;
}

export type PipelineStage =
  | 'idle'
  | 'refining-story'
  | 'extracting-characters'
  | 'generating-breakdown'
  | 'generating-dialogue'
  | 'complete'
  | 'error';

export interface PipelineStatus {
  stage: PipelineStage;
  currentPanel?: number;
  totalPanels?: number;
  message: string;
}

export const GENRE_OPTIONS: { value: Genre; label: string; emoji: string }[] = [
  { value: 'noir', label: 'Noir', emoji: '🕵️' },
  { value: 'manga', label: 'Manga', emoji: '⚔️' },
  { value: 'cyberpunk', label: 'Cyberpunk', emoji: '🤖' },
  { value: 'webtoon-romance', label: 'Webtoon Romance', emoji: '💕' },
  { value: 'superhero', label: 'Superhero', emoji: '🦸' },
  { value: 'fantasy', label: 'Fantasy', emoji: '🧙' },
  { value: 'comedy', label: 'Comedy', emoji: '😂' },
  { value: 'horror', label: 'Horror', emoji: '👻' },
  { value: 'sci-fi', label: 'Sci-Fi', emoji: '🚀' },
  { value: 'slice-of-life', label: 'Slice of Life', emoji: '☕' },
  { value: 'action', label: 'Action', emoji: '💥' },
  { value: 'drama', label: 'Drama', emoji: '🎭' },
];

export const FORMAT_OPTIONS: { value: TargetFormat; label: string; panels: number }[] = [
  { value: '3-panel-strip', label: '3-Panel Strip', panels: 3 },
  { value: '4-panel-strip', label: '4-Panel Strip', panels: 4 },
  { value: '6-panel-scene', label: '6-Panel Scene', panels: 6 },
  { value: '9-panel-page', label: '9-Panel Page', panels: 9 },
  { value: '12-panel-episode', label: '12-Panel Episode', panels: 12 },
];

export const DELIVERY_STYLES: { value: DeliveryStyle; label: string; icon: string }[] = [
  { value: 'normal', label: 'Normal', icon: '💬' },
  { value: 'shout', label: 'Shout', icon: '📢' },
  { value: 'whisper', label: 'Whisper', icon: '🤫' },
  { value: 'thought', label: 'Thought', icon: '💭' },
  { value: 'sarcastic', label: 'Sarcastic', icon: '😏' },
  { value: 'muttered', label: 'Muttered', icon: '😶' },
  { value: 'trembling', label: 'Trembling', icon: '😰' },
  { value: 'cold', label: 'Cold', icon: '🥶' },
  { value: 'excited', label: 'Excited', icon: '🤩' },
  { value: 'narration', label: 'Narration', icon: '📖' },
];

export function generateId(): string {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 8);
}

export function getFormatPanelCount(format: TargetFormat): number {
  return FORMAT_OPTIONS.find(f => f.value === format)?.panels ?? 6;
}

const AVATAR_COLORS = [
  '#6366f1', '#ec4899', '#f59e0b', '#10b981', '#ef4444',
  '#8b5cf6', '#14b8a6', '#f97316', '#06b6d4', '#e11d48',
  '#84cc16', '#a855f7',
];

export function getAvatarColor(index: number): string {
  return AVATAR_COLORS[index % AVATAR_COLORS.length];
}
