import { useState } from 'react';
import {
  Users,
  Sparkles,
  Plus,
  Edit3,
  Trash2,
  MessageCircle,
  Heart,
  Brain,
  Eye,
  ChevronDown,
  ChevronUp,
  Wand2,
  Loader2,
} from 'lucide-react';
import type { CharacterVoiceProfile } from '../types/comic';
import CharacterEditModal from './CharacterEditModal';

interface CharacterManagerProps {
  characters: CharacterVoiceProfile[];
  storyIdea: string;
  isExtracting: boolean;
  onExtractCharacters: () => void;
  onAddCharacter: (character: CharacterVoiceProfile) => void;
  onUpdateCharacter: (character: CharacterVoiceProfile) => void;
  onDeleteCharacter: (id: string) => void;
}

export default function CharacterManager({
  characters,
  storyIdea,
  isExtracting,
  onExtractCharacters,
  onAddCharacter,
  onUpdateCharacter,
  onDeleteCharacter,
}: CharacterManagerProps) {
  const [editingCharacter, setEditingCharacter] = useState<CharacterVoiceProfile | null>(null);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isCreating, setIsCreating] = useState(false);
  const [expandedCards, setExpandedCards] = useState<Set<string>>(new Set());

  const toggleExpanded = (id: string) => {
    setExpandedCards(prev => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const handleEdit = (char: CharacterVoiceProfile) => {
    setEditingCharacter(char);
    setIsCreating(false);
    setIsModalOpen(true);
  };

  const handleCreate = () => {
    setEditingCharacter(null);
    setIsCreating(true);
    setIsModalOpen(true);
  };

  const handleSave = (char: CharacterVoiceProfile) => {
    if (isCreating) {
      onAddCharacter(char);
    } else {
      onUpdateCharacter(char);
    }
  };

  return (
    <div className="character-manager">
      <div className="section-header">
        <Users size={20} />
        <h2>Characters</h2>
        <span className="badge">{characters.length}</span>
      </div>

      <div className="character-actions">
        <button
          className="btn btn-accent character-extract-btn"
          onClick={onExtractCharacters}
          disabled={isExtracting || !storyIdea.trim()}
        >
          {isExtracting ? (
            <>
              <Loader2 size={16} className="spin" />
              <span>Extracting...</span>
            </>
          ) : (
            <>
              <Wand2 size={16} />
              <span>Auto-Extract from Story</span>
            </>
          )}
        </button>
        <button className="btn btn-outline" onClick={handleCreate}>
          <Plus size={16} />
          <span>Add Manually</span>
        </button>
      </div>

      {characters.length === 0 ? (
        <div className="empty-characters">
          <Users size={48} className="empty-icon" />
          <p>No characters yet</p>
          <p className="empty-hint">
            Write your story above, then click "Auto-Extract" to let AI discover your characters, or add them manually.
          </p>
        </div>
      ) : (
        <div className="character-grid">
          {characters.map(char => {
            const isExpanded = expandedCards.has(char.id);
            return (
              <div
                key={char.id}
                className="character-card"
                style={{ '--char-color': char.avatarColor } as React.CSSProperties}
              >
                <div className="char-card-header">
                  <div className="char-avatar" style={{ background: char.avatarColor }}>
                    {char.name.charAt(0).toUpperCase()}
                  </div>
                  <div className="char-info">
                    <h3 className="char-name">{char.name}</h3>
                    {char.isAutoGenerated && (
                      <span className="char-auto-badge">
                        <Sparkles size={10} /> AI Generated
                      </span>
                    )}
                  </div>
                  <div className="char-card-actions">
                    <button className="btn-icon-sm" onClick={() => handleEdit(char)} title="Edit">
                      <Edit3 size={14} />
                    </button>
                    <button className="btn-icon-sm btn-danger" onClick={() => onDeleteCharacter(char.id)} title="Delete">
                      <Trash2 size={14} />
                    </button>
                  </div>
                </div>

                <div className="char-tags">
                  <div className="char-tag">
                    <Eye size={10} />
                    <span>{char.physical_description.slice(0, 60)}{char.physical_description.length > 60 ? '...' : ''}</span>
                  </div>
                  <div className="char-tag">
                    <Brain size={10} />
                    <span>{char.personality.slice(0, 50)}{char.personality.length > 50 ? '...' : ''}</span>
                  </div>
                  <div className="char-tag">
                    <MessageCircle size={10} />
                    <span>{char.speech_style.slice(0, 50)}{char.speech_style.length > 50 ? '...' : ''}</span>
                  </div>
                </div>

                {isExpanded && (
                  <div className="char-expanded">
                    <div className="char-detail">
                      <strong>Vocabulary:</strong> {char.vocabulary_level}
                    </div>
                    <div className="char-detail">
                      <strong>Emotional:</strong> {char.emotional_tendencies}
                    </div>
                    {Object.keys(char.relationships).length > 0 && (
                      <div className="char-relationships">
                        <strong><Heart size={12} /> Relationships:</strong>
                        {Object.entries(char.relationships).map(([name, rel]) => (
                          <div key={name} className="char-rel-chip">
                            <span className="rel-to">{name}:</span> {rel}
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                )}

                <button
                  className="char-expand-btn"
                  onClick={() => toggleExpanded(char.id)}
                >
                  {isExpanded ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
                  {isExpanded ? 'Less' : 'More'}
                </button>
              </div>
            );
          })}
        </div>
      )}

      <CharacterEditModal
        isOpen={isModalOpen}
        character={isCreating ? null : editingCharacter}
        allCharacters={characters}
        onClose={() => setIsModalOpen(false)}
        onSave={handleSave}
      />
    </div>
  );
}
