import { useState } from 'react';
import { X, Plus, Trash2, Save, User, MessageSquare, Brain, Heart, BookOpen, Palette } from 'lucide-react';
import type { CharacterVoiceProfile } from '../types/comic';
import { generateId, getAvatarColor } from '../types/comic';

interface CharacterEditModalProps {
  isOpen: boolean;
  character: CharacterVoiceProfile | null;
  allCharacters: CharacterVoiceProfile[];
  onClose: () => void;
  onSave: (character: CharacterVoiceProfile) => void;
}

export default function CharacterEditModal({
  isOpen,
  character,
  allCharacters,
  onClose,
  onSave,
}: CharacterEditModalProps) {
  const isNew = !character;
  const [form, setForm] = useState<CharacterVoiceProfile>(
    character || {
      id: generateId(),
      name: '',
      physical_description: '',
      personality: '',
      speech_style: '',
      vocabulary_level: '',
      emotional_tendencies: '',
      relationships: {},
      avatarColor: getAvatarColor(allCharacters.length),
      isAutoGenerated: false,
    }
  );

  const [newRelName, setNewRelName] = useState('');
  const [newRelDesc, setNewRelDesc] = useState('');

  if (!isOpen) return null;

  const update = (field: keyof CharacterVoiceProfile, value: string) => {
    setForm(prev => ({ ...prev, [field]: value }));
  };

  const addRelationship = () => {
    if (newRelName.trim() && newRelDesc.trim()) {
      setForm(prev => ({
        ...prev,
        relationships: { ...prev.relationships, [newRelName.trim()]: newRelDesc.trim() },
      }));
      setNewRelName('');
      setNewRelDesc('');
    }
  };

  const removeRelationship = (name: string) => {
    setForm(prev => {
      const rels = { ...prev.relationships };
      delete rels[name];
      return { ...prev, relationships: rels };
    });
  };

  const handleSave = () => {
    if (!form.name.trim()) return;
    onSave(form);
    onClose();
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal character-edit-modal" onClick={e => e.stopPropagation()}>
        <div className="modal-header">
          <h2>
            <User size={20} />
            {isNew ? 'Create Character' : `Edit: ${character?.name}`}
          </h2>
          <button className="modal-close" onClick={onClose}><X size={20} /></button>
        </div>

        <div className="modal-body character-form">
          <div className="form-row">
            <div className="form-group flex-2">
              <label><User size={14} /> Character Name</label>
              <input
                type="text"
                value={form.name}
                onChange={e => update('name', e.target.value)}
                placeholder="Detective Rao"
                className="form-input"
              />
            </div>
            <div className="form-group flex-1">
              <label><Palette size={14} /> Avatar Color</label>
              <input
                type="color"
                value={form.avatarColor}
                onChange={e => update('avatarColor', e.target.value)}
                className="form-color"
              />
            </div>
          </div>

          <div className="form-group">
            <label><User size={14} /> Physical Description</label>
            <textarea
              value={form.physical_description}
              onChange={e => update('physical_description', e.target.value)}
              placeholder="40s, tired eyes, trench coat, stubble..."
              className="form-textarea"
              rows={2}
            />
          </div>

          <div className="form-group">
            <label><Brain size={14} /> Personality</label>
            <textarea
              value={form.personality}
              onChange={e => update('personality', e.target.value)}
              placeholder="cynical, dry humor, emotionally guarded..."
              className="form-textarea"
              rows={2}
            />
          </div>

          <div className="form-group">
            <label><MessageSquare size={14} /> Speech Style</label>
            <textarea
              value={form.speech_style}
              onChange={e => update('speech_style', e.target.value)}
              placeholder="short clipped sentences, sarcastic under pressure..."
              className="form-textarea"
              rows={2}
            />
          </div>

          <div className="form-row">
            <div className="form-group flex-1">
              <label><BookOpen size={14} /> Vocabulary Level</label>
              <input
                type="text"
                value={form.vocabulary_level}
                onChange={e => update('vocabulary_level', e.target.value)}
                placeholder="streetwise, dark wit"
                className="form-input"
              />
            </div>
            <div className="form-group flex-1">
              <label><Heart size={14} /> Emotional Tendencies</label>
              <input
                type="text"
                value={form.emotional_tendencies}
                onChange={e => update('emotional_tendencies', e.target.value)}
                placeholder="masks vulnerability with humor"
                className="form-input"
              />
            </div>
          </div>

          <div className="form-group">
            <label><Heart size={14} /> Relationships</label>
            <div className="relationships-list">
              {Object.entries(form.relationships).map(([name, desc]) => (
                <div key={name} className="relationship-item">
                  <span className="rel-name">{name}</span>
                  <span className="rel-desc">{desc}</span>
                  <button className="btn-icon-sm" onClick={() => removeRelationship(name)}>
                    <Trash2 size={12} />
                  </button>
                </div>
              ))}
            </div>
            <div className="relationship-add">
              <input
                type="text"
                value={newRelName}
                onChange={e => setNewRelName(e.target.value)}
                placeholder="Character name"
                className="form-input form-input-sm"
              />
              <input
                type="text"
                value={newRelDesc}
                onChange={e => setNewRelDesc(e.target.value)}
                placeholder="Relationship dynamic"
                className="form-input form-input-sm"
                onKeyDown={e => e.key === 'Enter' && addRelationship()}
              />
              <button className="btn btn-sm btn-outline" onClick={addRelationship}>
                <Plus size={14} />
              </button>
            </div>
          </div>
        </div>

        <div className="modal-footer">
          <button className="btn btn-ghost" onClick={onClose}>Cancel</button>
          <button className="btn btn-primary" onClick={handleSave} disabled={!form.name.trim()}>
            <Save size={14} /> {isNew ? 'Create Character' : 'Save Changes'}
          </button>
        </div>
      </div>
    </div>
  );
}
