import { useState, useCallback } from 'react';
import type {
  StoryProject,
  CharacterVoiceProfile,
  LLMSettings,
  PipelineStatus,
} from './types/comic';
import { generateId } from './types/comic';
import { useLocalStorage } from './hooks/useLocalStorage';
import { createEmptyProject, SAMPLE_NOIR_PROJECT } from './data/sampleProjects';
import {
  refineStory,
  extractCharactersFromStory,
  generateFullScript,
  regeneratePanel,
} from './services/llmService';

import Navbar from './components/Navbar';
import SettingsModal from './components/SettingsModal';
import ExportModal from './components/ExportModal';
import StoryInputSection from './components/StoryInputSection';
import CharacterManager from './components/CharacterManager';
import ComicBoardView from './components/ComicBoardView';
import ScriptListView from './components/ScriptListView';
import ToastContainer, { showToast } from './components/Toast';

import { LayoutGrid, FileText, Loader2, Sparkles } from 'lucide-react';

type ViewMode = 'board' | 'script';

function App() {
  // Persistence
  const [project, setProject] = useLocalStorage<StoryProject>('storynex-project', createEmptyProject());
  const [llmSettings, setLlmSettings] = useLocalStorage<LLMSettings>('storynex-llm-settings', {
    apiKey: (import.meta.env.VITE_GROQ_API_KEY as string) || '',
    model: (import.meta.env.VITE_GROQ_MODEL as string) || 'llama-3.3-70b-versatile',
    temperature: 0.7,
    maxTokens: 4096,
  });

  // UI State
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [exportOpen, setExportOpen] = useState(false);
  const [viewMode, setViewMode] = useState<ViewMode>('board');
  const [isRefining, setIsRefining] = useState(false);
  const [isExtracting, setIsExtracting] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [regeneratingPanels, setRegeneratingPanels] = useState<Set<number>>(new Set());
  const [refinedStory, setRefinedStory] = useState<string | undefined>(project.refined_story);

  const [pipelineStatus, setPipelineStatus] = useState<PipelineStatus>({
    stage: 'idle',
    message: '',
  });

  // ── Project Management ──
  const updateProject = useCallback((updates: Partial<StoryProject>) => {
    setProject(prev => ({ ...prev, ...updates, updatedAt: new Date().toISOString() }));
  }, [setProject]);

  const handleNewProject = () => {
    setProject(createEmptyProject());
    setRefinedStory(undefined);
    setPipelineStatus({ stage: 'idle', message: '' });
    showToast('New project created', 'info');
  };

  const handleLoadSample = () => {
    setProject({ ...SAMPLE_NOIR_PROJECT, id: generateId(), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() });
    setRefinedStory(undefined);
    showToast('Sample noir project loaded!', 'success');
  };

  // ── Story Refinement ──
  const handleRefineStory = async () => {
    if (!project.story_idea.trim()) return;
    setIsRefining(true);
    setPipelineStatus({ stage: 'refining-story', message: 'AI is refining your story...' });
    try {
      const refined = await refineStory(project.story_idea, project.genre, llmSettings);
      setRefinedStory(refined);
      updateProject({ refined_story: refined });
      showToast('Story refined! Review the enhanced version below.', 'success');
    } catch (err) {
      showToast(`Refinement failed: ${err instanceof Error ? err.message : 'Unknown error'}`, 'error');
    } finally {
      setIsRefining(false);
      setPipelineStatus({ stage: 'idle', message: '' });
    }
  };

  const handleUseRefined = () => {
    if (refinedStory) {
      updateProject({ story_idea: refinedStory });
      setRefinedStory(undefined);
      showToast('Refined story applied!', 'success');
    }
  };

  // ── Character Management ──
  const handleExtractCharacters = async () => {
    if (!project.story_idea.trim()) return;
    setIsExtracting(true);
    setPipelineStatus({ stage: 'extracting-characters', message: 'AI is discovering characters...' });
    try {
      const extracted = await extractCharactersFromStory(project.story_idea, project.genre, llmSettings);
      // Merge: keep existing manually added, add new AI ones
      const existingManual = project.characters.filter(c => !c.isAutoGenerated);
      const merged = [...existingManual, ...extracted];
      updateProject({ characters: merged });
      showToast(`Extracted ${extracted.length} characters from your story!`, 'success');
    } catch (err) {
      showToast(`Character extraction failed: ${err instanceof Error ? err.message : 'Unknown error'}`, 'error');
    } finally {
      setIsExtracting(false);
      setPipelineStatus({ stage: 'idle', message: '' });
    }
  };

  const handleAddCharacter = (char: CharacterVoiceProfile) => {
    updateProject({ characters: [...project.characters, char] });
    showToast(`Added ${char.name}`, 'success');
  };

  const handleUpdateCharacter = (updated: CharacterVoiceProfile) => {
    updateProject({
      characters: project.characters.map(c => c.id === updated.id ? updated : c),
    });
    showToast(`Updated ${updated.name}`, 'success');
  };

  const handleDeleteCharacter = (id: string) => {
    const char = project.characters.find(c => c.id === id);
    updateProject({ characters: project.characters.filter(c => c.id !== id) });
    showToast(`Removed ${char?.name || 'character'}`, 'info');
  };

  // ── Script Generation Pipeline ──
  const handleGenerateScript = async () => {
    if (!project.story_idea.trim()) {
      showToast('Please enter a story idea first', 'error');
      return;
    }
    if (project.characters.length === 0) {
      showToast('Please add at least one character', 'error');
      return;
    }

    setIsGenerating(true);
    try {
      const panels = await generateFullScript(
        project.story_idea,
        project.characters,
        project.genre,
        project.target_format,
        llmSettings,
        (stage, current, total) => {
          if (stage === 'breakdown') {
            setPipelineStatus({
              stage: 'generating-breakdown',
              currentPanel: current,
              totalPanels: total,
              message: `Planning panel ${current} of ${total}...`,
            });
          } else if (stage === 'dialogue') {
            setPipelineStatus({
              stage: 'generating-dialogue',
              currentPanel: current,
              totalPanels: total,
              message: `Writing dialogue for panel ${current} of ${total}...`,
            });
          } else {
            setPipelineStatus({
              stage: 'complete',
              currentPanel: total,
              totalPanels: total,
              message: 'Script generation complete!',
            });
          }
        },
      );

      updateProject({ panels });
      setPipelineStatus({ stage: 'complete', message: 'Script generation complete!' });
      showToast(`Generated ${panels.length}-panel comic script!`, 'success');
    } catch (err) {
      setPipelineStatus({ stage: 'error', message: 'Generation failed' });
      showToast(`Generation failed: ${err instanceof Error ? err.message : 'Unknown error'}`, 'error');
    } finally {
      setIsGenerating(false);
      setTimeout(() => setPipelineStatus(prev => prev.stage === 'complete' ? { stage: 'idle', message: '' } : prev), 3000);
    }
  };

  // ── Panel Regeneration ──
  const handleRegeneratePanel = async (panelNumber: number, mode: 'scene' | 'dialogue' | 'both') => {
    const panel = project.panels.find(p => p.panel_number === panelNumber);
    if (!panel) return;

    setRegeneratingPanels(prev => new Set(prev).add(panelNumber));
    try {
      const updates = await regeneratePanel(
        panel,
        project.panels,
        project.characters,
        project.genre,
        mode,
        llmSettings,
      );

      const updatedPanels = project.panels.map(p =>
        p.panel_number === panelNumber ? { ...p, ...updates } : p
      );
      updateProject({ panels: updatedPanels });
      showToast(`Panel ${panelNumber} ${mode} regenerated!`, 'success');
    } catch (err) {
      showToast(`Regeneration failed: ${err instanceof Error ? err.message : 'Unknown error'}`, 'error');
    } finally {
      setRegeneratingPanels(prev => {
        const next = new Set(prev);
        next.delete(panelNumber);
        return next;
      });
    }
  };

  const canGenerate = project.story_idea.trim().length > 0 && project.characters.length > 0 && !isGenerating;

  return (
    <div className="app">
      <Navbar
        project={project}
        onOpenSettings={() => setSettingsOpen(true)}
        onOpenExport={() => setExportOpen(true)}
        onNewProject={handleNewProject}
        onLoadSample={handleLoadSample}
      />

      <main className="main-content">
        {/* Left Column: Setup */}
        <aside className="setup-panel">
          <StoryInputSection
            storyIdea={project.story_idea}
            refinedStory={refinedStory}
            genre={project.genre}
            targetFormat={project.target_format}
            title={project.title}
            isRefining={isRefining}
            onStoryChange={story => updateProject({ story_idea: story })}
            onGenreChange={genre => updateProject({ genre })}
            onFormatChange={format => updateProject({ target_format: format })}
            onTitleChange={title => updateProject({ title })}
            onRefineStory={handleRefineStory}
            onUseRefined={handleUseRefined}
          />

          <CharacterManager
            characters={project.characters}
            storyIdea={project.story_idea}
            isExtracting={isExtracting}
            onExtractCharacters={handleExtractCharacters}
            onAddCharacter={handleAddCharacter}
            onUpdateCharacter={handleUpdateCharacter}
            onDeleteCharacter={handleDeleteCharacter}
          />

          <div className="generate-section">
            <button
              className="btn btn-generate"
              onClick={handleGenerateScript}
              disabled={!canGenerate}
            >
              {isGenerating ? (
                <>
                  <Loader2 size={20} className="spin" />
                  <span>Generating...</span>
                </>
              ) : (
                <>
                  <Sparkles size={20} />
                  <span>Generate Comic Script</span>
                </>
              )}
            </button>
            {!canGenerate && !isGenerating && (
              <p className="generate-hint">
                {!project.story_idea.trim()
                  ? 'Enter a story idea to get started'
                  : 'Add at least one character'}
              </p>
            )}
          </div>
        </aside>

        {/* Right Column: Output */}
        <section className="output-panel">
          <div className="output-header">
            <div className="view-toggle">
              <button
                className={`view-toggle-btn ${viewMode === 'board' ? 'active' : ''}`}
                onClick={() => setViewMode('board')}
              >
                <LayoutGrid size={16} />
                Comic Board
              </button>
              <button
                className={`view-toggle-btn ${viewMode === 'script' ? 'active' : ''}`}
                onClick={() => setViewMode('script')}
              >
                <FileText size={16} />
                Script View
              </button>
            </div>

            {project.panels.length > 0 && (
              <span className="panel-count-badge">
                {project.panels.length} panels
              </span>
            )}
          </div>

          {viewMode === 'board' ? (
            <ComicBoardView
              panels={project.panels}
              characters={project.characters}
              pipelineStatus={pipelineStatus}
              regeneratingPanels={regeneratingPanels}
              onRegeneratePanel={handleRegeneratePanel}
            />
          ) : (
            <ScriptListView
              panels={project.panels}
              characters={project.characters}
            />
          )}
        </section>
      </main>

      {/* Modals */}
      <SettingsModal
        isOpen={settingsOpen}
        onClose={() => setSettingsOpen(false)}
        settings={llmSettings}
        onSave={setLlmSettings}
      />
      <ExportModal
        isOpen={exportOpen}
        onClose={() => setExportOpen(false)}
        project={project}
      />
      <ToastContainer />
    </div>
  );
}

export default App;
