import type { StoryProject, CharacterVoiceProfile } from '../types/comic';
import { generateId, getAvatarColor } from '../types/comic';

const SAMPLE_CHARACTERS: CharacterVoiceProfile[] = [
  {
    id: generateId(),
    name: 'Detective Rao',
    physical_description: '40s, tired eyes behind wire-rim glasses, rumpled trench coat, stubble, weathered hands',
    personality: 'cynical, dry humor, emotionally guarded but secretly compassionate',
    speech_style: 'short clipped sentences, rarely uses contractions when serious, sarcastic under pressure',
    vocabulary_level: 'streetwise, occasional dark literary references',
    emotional_tendencies: 'masks vulnerability with humor, slow-burning anger, rare genuine warmth',
    relationships: { 'Femme Fatale': 'distrustful but drawn to her' },
    avatarColor: getAvatarColor(0),
    isAutoGenerated: false,
  },
  {
    id: generateId(),
    name: 'The Femme Fatale',
    physical_description: 'early 30s, striking features, crimson lipstick, black cocktail dress, cigarette holder',
    personality: 'enigmatic, manipulative, surprisingly vulnerable underneath',
    speech_style: 'smooth and deliberate, uses double meanings, elongated vowels',
    vocabulary_level: 'sophisticated, theatrical, occasional French phrases',
    emotional_tendencies: 'controlled exterior masking deep pain, seductive when cornered, genuine grief in private',
    relationships: { 'Detective Rao': 'uses him but genuinely cares, complicated' },
    avatarColor: getAvatarColor(1),
    isAutoGenerated: false,
  },
];

export const SAMPLE_NOIR_PROJECT: StoryProject = {
  id: generateId(),
  title: 'Shadows of Chinatown',
  story_idea: 'A world-weary detective investigates a series of murders in the neon-lit underworld of a 1940s Chinatown. Each victim was last seen at the same jazz club, and the only witness is a mysterious woman who seems to know more than she lets on. As the detective digs deeper, he discovers the murders are connected to a decades-old secret that powerful people will kill to keep buried.',
  genre: 'noir',
  target_format: '6-panel-scene',
  characters: SAMPLE_CHARACTERS,
  panels: [],
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export function createEmptyProject(): StoryProject {
  return {
    id: generateId(),
    title: 'Untitled Project',
    story_idea: '',
    genre: 'noir',
    target_format: '6-panel-scene',
    characters: [],
    panels: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}
